### ISSUE TITLE
Update Citations

### ISSUE THREAD

**Issue by github-cloudlabsuser-493** [github-cloudlabsuser-493/blue-openai#19]
Citations should be more descriptive

**Comment by github-cloudlabsuser-911** [comment]
Azure Cognitive/AI  Search doesn't support Citations for all data sources. I can see that the response.choices[].message.context is empty and there should be a title or URL there. This is why we get the error when you set show_citations = True, because it's returning none.

**Comment by github-cloudlabsuser-493** [comment]
Citations show if you add title to the metadata in the storage account. I also had to re-create the index to look for the title metadata. Still some strange behavior around it but they should be showing now if you flip the flag to true
